# docker version 1.12.0+
# docker-compose version 1.9.0+
version: '2.1'

services:
  web:
    image: jwilder/nginx-proxy:alpine
    container_name: web
    mem_limit: 128m
    hostname: web
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
           - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - web-certs:/etc/nginx/certs
      - web-dhparam:/etc/nginx/dhparam
    restart: unless-stopped

  app:
    image: sharetribe
    container_name: app
    mem_limit: 2048m
    hostname: app
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - app
    volumes:
      - app:/opt/app/www
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${PORT-3000}"]
    restart: unless-stopped
    env_file: .env
    environment:
      - VIRTUAL_HOST=${RS_DOMAIN}
      - VIRTUAL_PORT=${PORT:-3000}

  worker:
    image: sharetribe
    container_name: worker
    mem_limit: 1024m
    hostname: worker
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - worker
          - search
    volumes:
      - app:/opt/app/www
    command: worker
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    env_file: .env

  mysql:
    image: mysql:5.7
    container_name: mysql
    mem_limit: 1024m
    hostname: mysql
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - mysql
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping"]
    restart: unless-stopped
    env_file: .env

  smtp:
    image: catatnight/postfix
    container_name: smtp
    mem_limit: 128m
    hostname: smtp
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - smtp
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    env_file: .env

  memcache:
    image: redis:3.2-alpine
    container_name: memcache
    mem_limit: 512m
    hostname: memcache
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - memcache
    volumes:
      - memcache:/data
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  adminer:
    image: adminer:standalone
    container_name: adminer
    mem_limit: 128m
    hostname: adminer
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - adminer
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  web-certs:
  web-dhparam:
  app:
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
  mysql:
  memcache:

networks:
  local:
